services:
  backend:
    build: ./backend
    container_name: expense-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=8000

  frontend:
      build: ./frontend
      container_name: expense-frontend
      ports:
        - "5173:5173"
      volumes:
        - ./frontend:/app
        - /app/node_modules
      depends_on:
        - backend


    # mongodb:
    #   image: mongo:7
    #   conatiner_name: expense-db
    #   volumes:
    #     - mongo-data:/data/db